Loading required package: splines

Attaching package: 'combinat'


	The following object(s) are masked from package:utils :

	 combn 


Attaching package: 'papply'


	The following object(s) are masked _by_ .GlobalEnv :

	 .Last 


Attaching package: 'imagemap'


	The following object(s) are masked from package:SignS2 :

	 imClose 

Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Read 1 item
Error in file(file, "r") : unable to open connection
In addition: Warning message:
cannot open file 'usevalidation', reason 'No such file or directory' 
Read 87 items
Read 87 items
sed: can't read validationcovariate: No such file or directory
Read 87 items
